# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ac8a687681cbf906989dcb5e8d30243e6c4fa1b522631e10383dac62f22d0f160044450c0f042f36779c3e6516bbb4902a03b29171e009d95e4ec236d888b5

test:
  secret_key_base: ce4a4f73dedce5d2834702cd7b4a268c839b63fd5b9c523159110b3d4ebc9d22ea042a7aad3ab65666c216881eca166ce195890a084b4aaf8ad9ada9dbb8aff7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
